# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcfd5a1bfe10af029f025c793e828e71083da1ef3acb3d8f2fabb3c409ebc44322b9213126906e2c661f056751d8aeb78f7aea616978b52845c014f6b5a8ac42

test:
  secret_key_base: 1e31ec1d270e3a670a4f5639a76b6e40d2bbecd18505284c8a0305104bedc11a10b9d777e3b85b1812ef92367e5373eadce98ec3c5f086a8a09b3847cace3404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
